/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cadastrodepessoas.view;

import com.cadastrodepessoas.dao.ILogDAO;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author mfernandes
 */
public class ConfigurarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfigurarView
     */
    public ConfigurarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        usuariosTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrNameLbl = new javax.swing.JLabel();
        usrSenhaLbl = new javax.swing.JLabel();
        novoBtn = new javax.swing.JButton();
        logofBtn = new javax.swing.JButton();
        administradorCbx = new javax.swing.JCheckBox();
        logTab = new javax.swing.JPanel();
        tipoLogDAOCbx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configurar");

        jLabel1.setText("usuario:");

        jLabel2.setText("senha:");

        usrNameLbl.setText("...");

        usrSenhaLbl.setText("***");

        novoBtn.setText("novo usuario");

        logofBtn.setText("logoff");

        administradorCbx.setText("administrador");
        administradorCbx.setEnabled(false);

        javax.swing.GroupLayout usuariosTabLayout = new javax.swing.GroupLayout(usuariosTab);
        usuariosTab.setLayout(usuariosTabLayout);
        usuariosTabLayout.setHorizontalGroup(
            usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(administradorCbx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(usuariosTabLayout.createSequentialGroup()
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosTabLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(novoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(logofBtn))
                    .addGroup(usuariosTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usrSenhaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        usuariosTabLayout.setVerticalGroup(
            usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosTabLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usrNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usrSenhaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administradorCbx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(usuariosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logofBtn)
                    .addComponent(novoBtn))
                .addGap(22, 22, 22))
        );

        tabPanel.addTab("Usuarios", usuariosTab);

        jLabel3.setText("Tipo de Arquivo");

        javax.swing.GroupLayout logTabLayout = new javax.swing.GroupLayout(logTab);
        logTab.setLayout(logTabLayout);
        logTabLayout.setHorizontalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(tipoLogDAOCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logTabLayout.setVerticalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTabLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLogDAOCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabPanel.addTab("Log", logTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getAdministradorCbx() {
        return administradorCbx;
    }

    public JPanel getLogTab() {
        return logTab;
    }

    public JButton getLogofBtn() {
        return logofBtn;
    }

    public JButton getNovoBtn() {
        return novoBtn;
    }

    public JTabbedPane getTabPanel() {
        return tabPanel;
    }

    public JLabel getUsrNameLbl() {
        return usrNameLbl;
    }

    public JLabel getUsrSenhaLbl() {
        return usrSenhaLbl;
    }

    public JPanel getUsuariosTab() {
        return usuariosTab;
    }

    public JComboBox<ILogDAO> getTipoLogDAOCbx() {
        return tipoLogDAOCbx;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administradorCbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel logTab;
    private javax.swing.JButton logofBtn;
    private javax.swing.JButton novoBtn;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JComboBox<ILogDAO> tipoLogDAOCbx;
    private javax.swing.JLabel usrNameLbl;
    private javax.swing.JLabel usrSenhaLbl;
    private javax.swing.JPanel usuariosTab;
    // End of variables declaration//GEN-END:variables
}
