/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cadastrodepessoas.view;

import com.cadastrodepessoas.presenter.patterns.strategy.IStrategyImportar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author mfernandes
 */
public class ImportarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ImportarView
     */
    public ImportarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        strategyImportarCbx = new javax.swing.JComboBox<>();
        iniciarBtn = new javax.swing.JButton();
        importarBtn = new javax.swing.JButton();
        tempoPrBar = new javax.swing.JProgressBar();
        totalPrBar = new javax.swing.JProgressBar();
        unidadePrBar = new javax.swing.JProgressBar();
        unidadeLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        erroLbl = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Importar Contatos");

        jLabel1.setText("fonte:");
        jLabel1.setToolTipText("");

        iniciarBtn.setText("iniciar");

        importarBtn.setText("importar");
        importarBtn.setEnabled(false);

        unidadePrBar.setMaximum(3000);

        unidadeLbl.setText("...");

        totalLbl.setText("Status");

        jLabel4.setText("Tempo Restante");

        erroLbl.setText("0 erros.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadePrBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLbl)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(totalPrBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempoPrBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unidadeLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(iniciarBtn)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(strategyImportarCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(importarBtn)))
                        .addContainerGap())))
            .addComponent(erroLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(strategyImportarCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidadeLbl)
                .addGap(9, 9, 9)
                .addComponent(unidadePrBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPrBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempoPrBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erroLbl)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getImportarBtn() {
        return importarBtn;
    }

    public JButton getIniciarBtn() {
        return iniciarBtn;
    }

    public JProgressBar getTempoPrBar() {
        return tempoPrBar;
    }

    public JLabel getTotalLbl() {
        return totalLbl;
    }

    public JProgressBar getTotalPrBar() {
        return totalPrBar;
    }

    public JLabel getUnidadeLbl() {
        return unidadeLbl;
    }

    public JProgressBar getUnidadePrBar() {
        return unidadePrBar;
    }

    public JComboBox<IStrategyImportar> getStrategyImportarCbx() {
        return strategyImportarCbx;
    }

    public JLabel getErroLbl() {
        return erroLbl;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erroLbl;
    private javax.swing.JButton importarBtn;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<IStrategyImportar> strategyImportarCbx;
    private javax.swing.JProgressBar tempoPrBar;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JProgressBar totalPrBar;
    private javax.swing.JLabel unidadeLbl;
    private javax.swing.JProgressBar unidadePrBar;
    // End of variables declaration//GEN-END:variables
}
