/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cadastrodepessoas.view;

import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author mfernandes
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        adicionarJMenu = new javax.swing.JMenuItem();
        listarJMenu = new javax.swing.JMenuItem();
        configurarJMenu = new javax.swing.JMenuItem();
        sairJMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opções");

        adicionarJMenu.setText("Adicionar");
        jMenu1.add(adicionarJMenu);

        listarJMenu.setText("Listar Pessoas");
        jMenu1.add(listarJMenu);

        configurarJMenu.setText("Configurar");
        jMenu1.add(configurarJMenu);

        sairJMenu.setText("Sair");
        jMenu1.add(sairJMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getDesktopPane() {
        return DesktopPane;
    }

    public JMenuItem getAdicionarJMenu() {
        return adicionarJMenu;
    }

    public JMenuItem getConfigurarJMenu() {
        return configurarJMenu;
    }

    public JMenuItem getListarJMenu() {
        return listarJMenu;
    }

    public JMenuItem getSairJMenu() {
        return sairJMenu;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem adicionarJMenu;
    private javax.swing.JMenuItem configurarJMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarJMenu;
    private javax.swing.JMenuItem sairJMenu;
    // End of variables declaration//GEN-END:variables
}
